#!/usr/bin/env bash

USERPROFILE=$(wslpath -a $(cmd.exe /Q /C "echo %userprofile%" 2>/dev/null))

echo $USERPROFILE

LOCALSETTINGS="$USERPROFILE/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"

echo $LOCALSETTINGS

diff settings.json "$LOCALSETTINGS"

